server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: ORDER_SERVICE
          uri: lb://ORDER_SERVICE
          predicates:
            - Path=/order/**
        - id: PAYMENT_SERVICE
          uri: lb://PAYMENT_SERVICE
          predicates:
            - Path=/payment/**
        - id: INVENTORY_SERVICE
          uri: lb://INVENTORY_SERVICE
          predicates:
            - Path=/inventory/**
        - id: CUSTOMER_SERVICE
          uri: lb://CUSTOMER_SERVICE
          predicates:
            - Path=/customer/**
        - id: PRODUCT_SERVICE
          uri: lb://PRODUCT_SERVICE
          predicates:
            - Path=/productCatalog/**
