server:
  port: 8761
   


spring:
  application:
    name: service-registry
eureka:
  server:
    renewalPercentThreshold: 0.9
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
